unit-config: &unit-config
  steps:
    - checkout
    - run:
        name: Install composer packages
        command: composer install
    - run:
        name: PHP unit tests
        command: php ./vendor/bin/phpunit

version: 2
jobs:
  php-5.6:
    <<: *unit-config
    docker:
      - image: circleci/php:5.6
  php-7.1:
    <<: *unit-config
    docker:
      - image: circleci/php:7.1
  php-7.2:
    <<: *unit-config
    docker:
      - image: circleci/php:7.2

workflows:
  version: 2
  units:
    jobs:
      - php-7.2