version: 2
jobs:
  php-7.2:
    docker:
      - image: circleci/php:7.2
    steps:
      - add_ssh_keys:
          fingerprints:
          - "5a:e3:95:53:00:18:24:2d:03:89:52:a1:ee:98:7b:27"
      - checkout
      - run:
          name: Install composer packages
          command: composer install
      - run:
          name: PHP unit tests
          command: php ./vendor/bin/phpunit

workflows:
  version: 2
  units:
    jobs:
      - php-7.2