unit-config: &unit-config
  steps:
    - add_ssh_keys:
      fingerprints:
        - "5a:e3:95:53:00:18:24:2d:03:89:52:a1:ee:98:7b:27"
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        - v1-dependencies-
    - run:
        name: Install composer packages
        command: composer install
    - save_cache:
        paths:
          - ./vendor
        key: v1-dependencies-{{ checksum "composer.json" }}
    - run:
        name: PHP unit tests
        command: php ./vendor/bin/phpunit

version: 2
jobs:
  php-5.6:
    <<: *unit-config
    docker:
      - image: circleci/php:5.6
  php-7.1:
    <<: *unit-config
    docker:
      - image: circleci/php:7.1
  php-7.2:
    <<: *unit-config
    docker:
      - image: circleci/php:7.2

workflows:
  version: 2
  units:
    jobs:
      - php-7.2